=== vancolate/baidu-input-skin-saved/BiSkinTool/XMLSchema/Style.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.baidu.com"
           xmlns="http://www.baidu.com"
           elementFormDefault="qualified">
  <xs:simpleType name="BiDataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="color"/>
      <xs:enumeration value="int"/>
      <xs:enumeration value="enum"/>
      <xs:enumeration value="point"/>
      <xs:enumeration value="rect"/>
      <xs:enumeration value="scale"/>
      <xs:enumeration value="external"/>
      <xs:enumeration value="style"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="BiFileExtension">
    <xs:restriction base="xs:string">
      <xs:enumeration value=".ini"/>
      <xs:enumeration value=".cnd"/>
      <xs:enumeration value=".pop"/>
      <xs:enumeration value=".css"/>
      <xs:enumeration value=".til"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="BiBool">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true"/>
      <xs:enumeration value="false"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="BiAttr">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name ="data_type" type ="BiDataType"/>
      <xs:element name ="description" type ="BiDescType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BiCategory">
    <xs:sequence>
      <xs:element name="attr" type="BiAttr" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="repeat" type="BiBool" default="false"/>
  </xs:complexType>

  <xs:complexType name="BiFile">
    <xs:sequence>
      <xs:element name="category" type="BiCategory" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="ext" type="BiFileExtension" use="required" />
  </xs:complexType>

  <xs:simpleType name="BiDescType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+:.+)|([0-9]+-[0-9]+)|(\..+)"/>
    </xs:restriction>
  </xs:simpleType>
  
    
  <xs:element name="files">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="file" type ="BiFile" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vancolate/baidu-input-skin-saved/BiSkinTool/XMLSchema/Style.xml
<?xml version="1.0" encoding="utf-8"?>
<files xmlns="http://www.baidu.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.baidu.com Style.xsd">
  <file ext=".cnd">
    <category name="CAND" repeat="false">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>CELL_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>PADDING</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>FIRST_GAP</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>FIRST_FORE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FIRST_BACK</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>ICON_NUM</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>MORE_W</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>CELL_W</name>
        <data_type>int</data_type>
      </attr>
    </category>
    <category name="SWITCH" repeat="false">
      <attr>
        <name>NML_BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>SEL_BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>NML_FONT_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>SEL_FONT_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>PADDING</name>
        <data_type>int</data_type>
      </attr>
    </category>
    <category name="ICON" repeat="true">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>SIZE</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>POS</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>KEY</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>ANCHOR_TYPE</name>
        <data_type>int</data_type>
        <description>1-9</description>
      </attr>
      <attr>
        <name>PERSIST</name>
        <data_type>enum</data_type>
        <description>0:都不显示;1:无候选字时显示(建议为默认值);2:有候选字显示;3:有无候选字时都显示</description>
      </attr>
    </category>
  </file>
  <file ext=".ini">
    <category name="INPUT" repeat="false">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>PADDING</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>POS</name>
        <data_type>point</data_type>
      </attr>
    </category>
    <category name="CAND" repeat="false">
      <attr>
        <name>VIEW_RECT</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>LAYOUT_NAME</name>
        <data_type>external</data_type>
        <description>.cnd</description>
      </attr>
      <attr>
        <name>TYPE</name>
        <data_type>enum</data_type>
        <description>0:Candidate可处于面板内,通过划动选择候选字(划选皮肤);1:Candidate可处于面板内;2:Candidate固定于面板上方;3: 候选条处于面板内,常驻显示;4: 候选条处于面板上方,常驻显示;</description>
      </attr>
    </category>
    <category name="PANEL" repeat="false">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>SIZE</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>NO_BLUR</name>
        <data_type>enum</data_type>
        <description>0:模糊输入;1:精确输入</description>
      </attr>
      <attr>
        <name>KEY_NUM</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>TIP_NUM</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>BAR_H</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>CUSTOM_RECT</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>OFFSET_NUM</name>
        <data_type>int</data_type>
      </attr>
    </category>
    <category name="MORE" repeat="false">
      <attr>
        <name>GRID</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>HLINE_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>VLINE_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>LOCK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>SYM_LAYOUT</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>LAYOUT_NAME</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>CELL_STYLE</name>
        <data_type>style</data_type>
      </attr>
    </category>
    <category name="HINT" repeat="false">
      <attr>
        <name>LAYOUT_NAME</name>
        <data_type>external</data_type>
        <description>.pop</description>
      </attr>
      <attr>
        <name>TYPE</name>
        <data_type>enum</data_type>
        <description>0:跟随;1:置顶</description>
      </attr>
    </category>
    <category name="LIST" repeat="false">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>CELL_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>SCROLL_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>CELL_SIZE</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>POS</name>
        <data_type>point</data_type>
      </attr>
      <attr>
        <name>TYPE</name>
        <data_type>enum</data_type>
        <description>0:标准类型,处于面板内,永久显示;1:处于面板内,有列表项时显示;2:处于面板上方，始终显示;3:处于面板上方,有列表项时才显示</description>
      </attr>
      <attr>
        <name>LIST_NUM</name>
        <data_type>int</data_type>
      </attr>
      <attr>
        <name>LIST_ORDER</name>
        <data_type>enum</data_type>
        <description>0:竖排;1:横排</description>
      </attr>
      <attr>
        <name>NAMES</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>VALUES</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>PADDING</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>SCROLL_SIDE</name>
        <data_type>enum</data_type>
        <description>0:默认,对应向内;1:对应向外</description>
      </attr>
    </category>
    <category name="KEY" repeat="true">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>POS_TYPE</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>VIEW_RECT</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>TOUCH_RECT</name>
        <data_type>rect</data_type>
      </attr>
      <attr>
        <name>UP</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>DOWN</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>LEFT</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>RIGHT</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>CENTER</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>SHOW</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>HOLD</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>HOLDSYM</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>STAT_STYLE</name>
        <data_type>string</data_type>
      </attr>
    </category>
    <category name="TIP" repeat="true">
      <attr>
        <name>BACK_STYLE</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>FORE_STYLE</name>
        <data_type>forestyle</data_type>
      </attr>
      <attr>
        <name>CENTER</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>HOLD</name>
        <data_type>string</data_type>
      </attr>
      <attr>
        <name>SHOW</name>
        <data_type>string</data_type>
      </attr>
    </category>
    <category name="OFFSET" repeat="true">
      <attr>
        <name>POS</name>
        <data_type>point</data_type>
      </attr>
    </category>
  </file>
  <file ext=".pop">
    <category name="GLOBAL" repeat="false">
      <attr>
        <name>ICON_NUM</name>
        <data_type>int</data_type>
      </attr>
    </category>
    <category name="HINT" repeat="false">
      <attr>
        <name>BACK_ICON</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>ARROW_ICON</name>
        <data_type>style</data_type>
      </attr>
    </category>
    <category name="BAR" repeat="false">
      <attr>
        <name>BACK_ICON</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>ARROW_ICON</name>
        <data_type>style</data_type>
      </attr>
      <attr>
        <name>CELL_STYLE</name>
        <data_type>style</data_type>
      </attr>
    </category>
